#!/usr/bin/env python3
"""
Test intent classification accuracy using real production queries.
"""
import json

def classify_question_intent(question: str) -> str:
    q_lower = question.lower()
    
    # High-priority product keywords (check first)
    strong_product_keywords = ["hashicorp", "terraform", "vault", "consul", "vendor", "license"]
    if any(kw in q_lower for kw in strong_product_keywords):
        return "product_v1"
    
    # Calendar keywords (check second)
    calendar_keywords = [
        "meeting", "recording", "calendar", "event", "call", "invite", "invited",
        "owner of", "participant", "attendee", "transcript", "scheduled"
    ]
    if any(kw in q_lower for kw in calendar_keywords):
        return "calendar_v1"
    
    # Product keywords (broader, check third)
    product_keywords = ["product", "purchased", "bought", "acquired", "solution"]
    if any(kw in q_lower for kw in product_keywords):
        return "product_v1"
    
    # Sales keywords (check fourth)
    sales_keywords = [
        "deal", "revenue", "closed won", "closed lost", "win rate",
        "top selling", "best performing", "successful deals"
    ]
    if any(kw in q_lower for kw in sales_keywords):
        return "sales_v1"
    
    # Default: strict_v1 for ambiguous queries (pipeline, opportunities)
    return "strict_v1"

# Real production queries with correct intent labels
PRODUCTION_TEST_SET = [
    ("How many failed opportunities were there in 2025?", "strict_v1"),
    ("What is the total revenue generated by all clients in Region 'North'?", "sales_v1"),
    ("Who is the owner of the CalendarEvent with ID 123?", "calendar_v1"),
    ("How many Product installations are linked to Vendor 'ABC'?", "product_v1"),
    ("Which Employee has managed by the most Opportunities?", "strict_v1"),
    ("What is the count of ScanMetadata records for Products manufactured after 2020?", "product_v1"),
    ("Who is invited to the most CalendarEvents scheduled in Region 'South'?", "calendar_v1"),
    ("What is the average Skill level required for all OPPORTUNITY nodes?", "strict_v1"),
    ("How many Recording sessions have been linked to Client 'XYZ'?", "calendar_v1"),
    ("Which BU has the most SyncMetadata records?", "strict_v1"),
    ("What is the count of Employee assignments that are also Skills?", "strict_v1"),
    ("Who has installed the most Products in Region 'East'?", "product_v1"),
    ("How many Vendor opportunities have a status of 'Won'?", "product_v1"),
    ("What is the total number of Employees who can be InvitedTo CalendarEvents in Region 'West'?", "calendar_v1"),
    ("Which Client has the most OPPORTUNITY nodes linked to them?", "strict_v1"),
    ("What is the count of Product installations with a Vendor that belongs to Region 'North'?", "product_v1"),
    ("How many Employee activities have been assigned to Opportunities in Region 'South'?", "strict_v1"),
    ("Who owns the most Recordings in Region 'East'?", "calendar_v1"),
    ("What is the average Skill level required for all Employees who are InvitedTo CalendarEvents?", "calendar_v1"),
    ("Which BU has the fewest SyncMetadata records?", "strict_v1"),
]

def main():
    correct = 0
    total = len(PRODUCTION_TEST_SET)
    misclassifications = []
    stats = {"sales_v1": {"correct": 0, "total": 0}, "calendar_v1": {"correct": 0, "total": 0}, 
             "product_v1": {"correct": 0, "total": 0}, "strict_v1": {"correct": 0, "total": 0}}
    
    for query, expected in PRODUCTION_TEST_SET:
        predicted = classify_question_intent(query)
        is_correct = predicted == expected
        
        stats[expected]["total"] += 1
        if is_correct:
            correct += 1
            stats[expected]["correct"] += 1
        else:
            misclassifications.append({"query": query, "expected": expected, "predicted": predicted})
        
        status = "✓" if is_correct else "✗"
        print(f"{expected} -> {predicted} {status}: {query[:60]}")
    
    print(f"\n{'='*70}")
    print(f"RESULTS: {correct}/{total} ({int(correct/total*100)}%)")
    for intent in ["sales_v1", "calendar_v1", "product_v1", "strict_v1"]:
        s = stats[intent]
        pct = int(s["correct"]/s["total"]*100) if s["total"] > 0 else 0
        print(f"  {intent}: {s['correct']}/{s['total']} ({pct}%)")
    
    with open('production_intent_test.json', 'w') as f:
        json.dump({"accuracy": int(correct/total*100), "stats": stats, "misclassifications": misclassifications}, f, indent=2)
    
    print(f"\nSaved to: production_intent_test.json")

if __name__ == "__main__":
    main()
