"""
Step 2: Run generated queries against real API.
Reads queries from generated_queries.json and executes them.
"""
import json
import requests
import time
from pathlib import Path

API_URL = "http://localhost:8002/api/v1/query"  # Change to your Docker host if needed
# For remote Docker: "http://<server-ip>:8002/api/v1/query"
INPUT_FILE = "generated_queries.json"

def load_queries(filename: str):
    """Load and validate queries from JSON file."""
    if not Path(filename).exists():
        print(f"ERROR: {filename} not found")
        print("Run: python Tests/generate_queries_dgx.py first")
        return []
    
    try:
        with open(filename, 'r') as f:
            data = json.load(f)
        
        # Validate structure
        required_keys = ["generated_count", "model", "dgx_host", "queries"]
        for key in required_keys:
            if key not in data:
                print(f"ERROR: Missing key '{key}' in JSON")
                return []
        
        # Validate queries
        if not isinstance(data["queries"], list):
            print("ERROR: 'queries' must be a list")
            return []
        
        if len(data["queries"]) != data["generated_count"]:
            print(f"WARNING: Count mismatch - expected {data['generated_count']}, got {len(data['queries'])}")
        
        # Filter valid queries
        valid_queries = [q for q in data["queries"] if isinstance(q, str) and len(q) > 5]
        
        print(f"Loaded {len(valid_queries)} valid queries")
        print(f"Generated by: {data['model']} on {data['dgx_host']}")
        
        return valid_queries
        
    except json.JSONDecodeError as e:
        print(f"ERROR: Invalid JSON format: {e}")
        return []
    except Exception as e:
        print(f"ERROR: Failed to load queries: {e}")
        return []

def send_query(query: str):
    """Send query to API."""
    try:
        response = requests.post(
            API_URL,
            json={"query": query, "use_ai": True},
            timeout=30
        )
        return {
            "query": query,
            "success": response.status_code == 200,
            "status": response.status_code,
            "response": response.json() if response.status_code == 200 else None
        }
    except Exception as e:
        return {
            "query": query,
            "success": False,
            "error": str(e)
        }

def run_queries(queries: list, delay: float = 3.0):
    """Run queries with delay."""
    print(f"\nRunning {len(queries)} queries...")
    print("=" * 60)
    
    results = []
    for i, query in enumerate(queries, 1):
        print(f"\n[{i}/{len(queries)}] {query}")
        
        result = send_query(query)
        results.append(result)
        
        if result["success"]:
            resp = result["response"]
            method = resp.get('method', 'unknown')
            data_count = len(resp.get('data', []))
            exec_time = resp.get('execution_time', 0)
            print(f"  ✓ {method} - {data_count} results - {exec_time:.2f}s")
        else:
            error = result.get('error', 'Unknown')
            print(f"  ✗ Failed: {error}")
        
        if i < len(queries):
            time.sleep(delay)
    
    return results

def save_results(results: list):
    """Save results to file."""
    output_file = "query_results.json"
    with open(output_file, 'w') as f:
        json.dump(results, f, indent=2)
    print(f"\nResults saved to: {output_file}")

def print_summary(results: list):
    """Print summary."""
    print("\n" + "=" * 60)
    print("SUMMARY")
    print("=" * 60)
    
    total = len(results)
    success = sum(1 for r in results if r["success"])
    
    print(f"Total: {total}")
    print(f"Success: {success} ({success/total*100:.1f}%)")
    print(f"Failed: {total - success}")
    
    if total - success > 0:
        print("\nFailed queries:")
        for r in results:
            if not r["success"]:
                print(f"  - {r['query'][:60]}...")
    
    print("\n" + "=" * 60)
    print("Dashboard: http://localhost:8002/dashboard")
    print("=" * 60)

def main():
    print("=" * 60)
    print("Query Runner (Step 2)")
    print("=" * 60)
    
    # Check API
    try:
        response = requests.get("http://localhost:8002/health", timeout=5)
        if response.status_code != 200:
            print("ERROR: API not running")
            return
        print("✓ API available")
    except:
        print("ERROR: API not running")
        return
    
    # Load queries
    queries = load_queries(INPUT_FILE)
    if not queries:
        return
    
    print(f"✓ Loaded {len(queries)} queries\n")
    
    # Run
    results = run_queries(queries, delay=3.0)
    
    # Save results
    save_results(results)
    
    # Summary
    print_summary(results)

if __name__ == "__main__":
    main()
